version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - noctx
    - bodyclose
    - unconvert
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
        - unusedwrite
        - nilness
    staticcheck:
      checks:
        - all
        - -SA1019
        - -ST1000
        - -ST1020
        - -ST1021
        - -ST1018
        - -SA4006
        - -SA5011
        - -SA1012
        - -SA2001
        - -SA4011
        - -S1039
        - -S1011
        - -S1034
        - -QF1003
        - -QF1011
        - -S1008
        - -S1017
        - -SA9003
        - -QF1004
        - -QF1012
        - -QF1002
        - -QF1008
        - -QF1001
        - -SA4017
  exclusions:
    paths:
      - .gomodcache
      - vendor
    rules:
      - path: _test\.go
        linters:
          - noctx
          - bodyclose
          - errcheck
          - unused
      - path: cmd/
        linters:
          - noctx

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
