package pi

import (
	"context"
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/GrayCodeAI/trace/cli/agent"
	"github.com/GrayCodeAI/trace/cli/paths"
)

// Compile-time interface assertion
var _ agent.HookSupport = (*PiAgent)(nil)

//go:embed trace_extension.ts
var extensionTemplate string

const (
	// extensionDirName is the directory pi auto-discovers project-local
	// extensions from.
	extensionDirName = ".pi/extensions/trace"

	// extensionFileName is the file pi loads from extensionDirName.
	extensionFileName = "index.ts"

	// entireMarker identifies the file as Entire-owned. Substring of the
	// auto-generated header so AreHooksInstalled can verify ownership by
	// content (and so it survives the TRACE_CMD placeholder substitution).
	entireMarker = "Auto-generated by `trace enable --agent pi`"

	// entireCmdPlaceholder is replaced at install time with either `trace`
	// (production) or a `go run …` path (local-dev).
	entireCmdPlaceholder = "__TRACE_CMD__"
)

func extensionPath(ctx context.Context) (string, error) {
	root, err := paths.WorktreeRoot(ctx)
	if err != nil {
		// Fall back to CWD for tests run outside a git repo.
		//nolint:forbidigo // explicit fallback when WorktreeRoot fails
		root, err = os.Getwd()
		if err != nil {
			return "", fmt.Errorf("resolve repo root: %w", err)
		}
	}
	return filepath.Join(root, extensionDirName, extensionFileName), nil
}

func renderExtension(localDev bool) string {
	var cmd string
	if localDev {
		cmd = `go run "$(git rev-parse --show-toplevel)"/cmd/hawk trace`
	} else {
		cmd = "hawk trace"
	}
	return strings.ReplaceAll(extensionTemplate, entireCmdPlaceholder, cmd)
}

// InstallHooks writes the Trace pi extension to .pi/extensions/trace/index.ts.
// Returns 1 if the extension was written, 0 if already up-to-date (idempotent).
// If the file exists but content differs (e.g., localDev vs production), it is
// rewritten as long as it is recognisable as Entire-owned (contains the
// marker). A foreign file at the same path is left untouched unless force is
// true — this protects user-authored extensions that happen to live at
// .pi/extensions/trace/index.ts.
func (a *PiAgent) InstallHooks(ctx context.Context, localDev bool, force bool) (int, error) {
	path, err := extensionPath(ctx)
	if err != nil {
		return 0, err
	}
	content := renderExtension(localDev)

	if !force {
		// #nosec G304 -- path constructed from validated repo root
		existing, readErr := os.ReadFile(path)
		switch {
		case readErr == nil && string(existing) == content:
			return 0, nil // already up-to-date
		case readErr == nil && !strings.Contains(string(existing), entireMarker):
			return 0, fmt.Errorf("refusing to overwrite foreign file at %s; remove it or pass --force", path)
		}
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return 0, fmt.Errorf("create extension dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return 0, fmt.Errorf("write extension: %w", err)
	}
	return 1, nil
}

// UninstallHooks removes the entire pi extension directory (if present).
func (a *PiAgent) UninstallHooks(ctx context.Context) error {
	path, err := extensionPath(ctx)
	if err != nil {
		return err
	}
	dir := filepath.Dir(path)
	if err := os.RemoveAll(dir); err != nil {
		return fmt.Errorf("remove pi extension dir: %w", err)
	}
	return nil
}

// AreHooksInstalled returns true when the extension file exists and is
// recognisable as Entire-owned (contains the marker string).
func (a *PiAgent) AreHooksInstalled(ctx context.Context) bool {
	path, err := extensionPath(ctx)
	if err != nil {
		return false
	}
	// #nosec G304 -- path from validated repo root
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), entireMarker)
}
